spring.application.name=Where-is-My-Bus
wimb.admin.username=${ADMIN_USERNAME}
wimb.admin.password=${ADMIN_PASSWORD}

# ── PostgreSQL (Neon) ──
spring.datasource.url=jdbc:postgresql://ep-calm-wave-aqgziqbr-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hxG83aSDAWkV
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ── Upstash Redis ──
spring.data.redis.host=subtle-lynx-172210.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAqCyAAIgcDE1NDgzZDBlMWU5Y2Q0OTRhYTg3MWI1ZTNjZDMwMGRjOA
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=2000ms

# application.properties
wimb.depot.file.path=data/depot-codes.xlsx

# Directory where admin-uploaded route Excel files are stored (outside the build)
wimb.route.dir=data/routes